# Generated by Django 2.0.7 on 2018-07-07 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180706_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movrotativo',
            old_name='veiculos',
            new_name='veiculo',
        ),
    ]
